package com.Mat.TotalWarChess.imagesSetter;

import com.Mat.TotalWarChess.Model.ChessMoves;
import com.Mat.TotalWarChess.Model.FigureImage;
import jakarta.servlet.http.HttpSession;
import org.springframework.ui.Model;

public class ImagesSetter {

   public Model imagesSetter(Model model, HttpSession session) {
       ChessMoves chessMoves = (ChessMoves) session.getAttribute("chessMoves");
       if (chessMoves == null) {
           chessMoves = new ChessMoves();
           session.setAttribute("chessMoves", chessMoves);
       }

        // CREATING FIGURES 1 ROW

        FigureImage figureImage1_1 = new FigureImage("cell1_1", "cell1_1_img", "images/shaman.png");
        FigureImage figureImage1_2 = new FigureImage("cell1_2", "cell1_2_img", "images/hound.png");
        FigureImage figureImage1_3 = new FigureImage("cell1_3", "cell1_3_img", "images/troll.png");
        FigureImage figureImage1_4 = new FigureImage("cell1_4", "cell1_4_img", "images/black_orcs.png");
        FigureImage figureImage1_5 = new FigureImage("cell1_5", "cell1_5_img", "images/troll.png");
        FigureImage figureImage1_6 = new FigureImage("cell1_6", "cell1_6_img", "images/chariot.png");
       FigureImage figureImage1_7 = new FigureImage("cell1_7", "cell1_7_img", "images/shaman.png");
       FigureImage figureImage1_8 = new FigureImage("cell1_8", "cell1_8_img", "images/boyz.png");
       FigureImage figureImage1_9 = new FigureImage("cell1_9", "cell1_9_img", "images/blank.png");
       FigureImage figureImage1_10 = new FigureImage("cell1_10", "cell1_10_img", "images/cavalry_orcs.png");
       FigureImage figureImage1_11 = new FigureImage("cell1_11", "cell1_11_img", "images/black_orcs.png");
       FigureImage figureImage1_12 = new FigureImage("cell1_12", "cell1_12_img", "images/warlord.png");
       FigureImage figureImage1_13 = new FigureImage("cell1_13", "cell1_13_img", "images/shaman.png");
       FigureImage figureImage1_14 = new FigureImage("cell1_14", "cell1_14_img", "images/black_orcs.png");
       FigureImage figureImage1_15 = new FigureImage("cell1_15", "cell1_15_img", "images/cavalry_orcs.png");
       FigureImage figureImage1_16 = new FigureImage("cell1_16", "cell1_16_img", "images/blank.png");
       FigureImage figureImage1_17 = new FigureImage("cell1_17", "cell1_17_img", "images/troll.png");
       FigureImage figureImage1_18 = new FigureImage("cell1_18", "cell1_18_img", "images/chariot.png");
       FigureImage figureImage1_19 = new FigureImage("cell1_19", "cell1_19_img", "images/hound.png");
       FigureImage figureImage1_20 = new FigureImage("cell1_20", "cell1_20_img", "images/chariot.png");
       FigureImage figureImage1_21 = new FigureImage("cell1_21", "cell1_21_img", "images/hound.png");
       FigureImage figureImage1_22 = new FigureImage("cell1_22", "cell1_22_img", "images/chariot.png");
       FigureImage figureImage1_23 = new FigureImage("cell1_23", "cell1_23_img", "images/hound.png");
       FigureImage figureImage1_24 = new FigureImage("cell1_24", "cell1_24_img", "images/troll.png");
       // 2 ROW
       FigureImage figureImage2_1 = new FigureImage("cell2_1", "cell2_1_img", "images/boyz.png");
       FigureImage figureImage2_2 = new FigureImage("cell2_2", "cell2_2_img", "images/ogre_head.png");
       FigureImage figureImage2_3 = new FigureImage("cell2_3", "cell2_3_img", "images/cuggle.png");
       FigureImage figureImage2_4 = new FigureImage("cell2_4", "cell2_4_img", "images/boyz.png");
       FigureImage figureImage2_5 = new FigureImage("cell2_5", "cell2_5_img", "images/boyz.png");
       FigureImage figureImage2_6 = new FigureImage("cell2_6", "cell2_6_img", "images/ogre_head.png");
       FigureImage figureImage2_7 = new FigureImage("cell2_7", "cell2_7_img", "images/cuggle.png");
       FigureImage figureImage2_8 = new FigureImage("cell2_8", "cell2_8_img", "images/boyz.png");
       FigureImage figureImage2_9 = new FigureImage("cell2_9", "cell2_9_img", "images/blank.png");
       FigureImage figureImage2_10 = new FigureImage("cell2_10", "cell2_10_img", "images/boyz.png");
       FigureImage figureImage2_11 = new FigureImage("cell2_11", "cell2_11_img", "images/boyz.png");
       FigureImage figureImage2_12 = new FigureImage("cell2_12", "cell2_12_img", "images/boyz.png");
       FigureImage figureImage2_13 = new FigureImage("cell2_13", "cell2_13_img", "images/boyz.png");
       FigureImage figureImage2_14 = new FigureImage("cell2_14", "cell2_14_img", "images/boyz.png");
       FigureImage figureImage2_15 = new FigureImage("cell2_15", "cell2_15_img", "images/boyz.png");
       FigureImage figureImage2_16 = new FigureImage("cell2_16", "cell2_16_img", "images/blank.png");
       FigureImage figureImage2_17 = new FigureImage("cell2_17", "cell2_17_img", "images/boyz.png");
       FigureImage figureImage2_18 = new FigureImage("cell2_18", "cell2_18_img", "images/boyz.png");
       FigureImage figureImage2_19 = new FigureImage("cell2_19", "cell2_19_img", "images/boyz.png");
       FigureImage figureImage2_20 = new FigureImage("cell2_20", "cell2_20_img", "images/boyz.png");
       FigureImage figureImage2_21 = new FigureImage("cell2_21", "cell2_21_img", "images/boyz.png");
       FigureImage figureImage2_22 = new FigureImage("cell2_22", "cell2_22_img", "images/boyz.png");
       FigureImage figureImage2_23 = new FigureImage("cell2_23", "cell2_23_img", "images/boyz.png");
       FigureImage figureImage2_24 = new FigureImage("cell2_24", "cell2_24_img", "images/boyz.png");
       // 3 ROW
          FigureImage figureImage3_1 = new FigureImage("cell3_1", "cell3_1_img", "images/blank.png");
       FigureImage figureImage3_2 = new FigureImage("cell3_2", "cell3_2_img", "images/blank.png");
       FigureImage figureImage3_3 = new FigureImage("cell3_3", "cell3_3_img", "images/blank.png");
       FigureImage figureImage3_4 = new FigureImage("cell3_4", "cell3_4_img", "images/blank.png");
       FigureImage figureImage3_5 = new FigureImage("cell3_5", "cell3_5_img", "images/blank.png");
       FigureImage figureImage3_6 = new FigureImage("cell3_6", "cell3_6_img", "images/blank.png");
       FigureImage figureImage3_7 = new FigureImage("cell3_7", "cell3_7_img", "images/blank.png");
       FigureImage figureImage3_8 = new FigureImage("cell3_8", "cell3_8_img", "images/blank.png");
       FigureImage figureImage3_9 = new FigureImage("cell3_9", "cell3_9_img", "images/blank.png");
       FigureImage figureImage3_10 = new FigureImage("cell3_10", "cell3_10_img", "images/blank.png");
       FigureImage figureImage3_11 = new FigureImage("cell3_11", "cell3_11_img", "images/blank.png");
       FigureImage figureImage3_12 = new FigureImage("cell3_12", "cell3_12_img", "images/blank.png");
       FigureImage figureImage3_13 = new FigureImage("cell3_13", "cell3_13_img", "images/blank.png");
       FigureImage figureImage3_14 = new FigureImage("cell3_14", "cell3_14_img", "images/blank.png");
       FigureImage figureImage3_15 = new FigureImage("cell3_15", "cell3_15_img", "images/blank.png");
       FigureImage figureImage3_16 = new FigureImage("cell3_16", "cell3_16_img", "images/blank.png");
       FigureImage figureImage3_17 = new FigureImage("cell3_17", "cell3_17_img", "images/blank.png");
       FigureImage figureImage3_18 = new FigureImage("cell3_18", "cell3_18_img", "images/blank.png");
       FigureImage figureImage3_19 = new FigureImage("cell3_19", "cell3_19_img", "images/blank.png");
       FigureImage figureImage3_20 = new FigureImage("cell3_20", "cell3_20_img", "images/blank.png");
       FigureImage figureImage3_21 = new FigureImage("cell3_21", "cell3_21_img", "images/blank.png");
       FigureImage figureImage3_22 = new FigureImage("cell3_22", "cell3_22_img", "images/blank.png");
       FigureImage figureImage3_23 = new FigureImage("cell3_23", "cell3_23_img", "images/blank.png");
       FigureImage figureImage3_24 = new FigureImage("cell3_24", "cell3_24_img", "images/blank.png");
       // 4 ROW
         FigureImage figureImage4_1 = new FigureImage("cell4_1", "cell4_1_img", "images/blank.png");
       FigureImage figureImage4_2 = new FigureImage("cell4_2", "cell4_2_img", "images/blank.png");
       FigureImage figureImage4_3 = new FigureImage("cell4_3", "cell4_3_img", "images/blank.png");
       FigureImage figureImage4_4 = new FigureImage("cell4_4", "cell4_4_img", "images/blank.png");
       FigureImage figureImage4_5 = new FigureImage("cell4_5", "cell4_5_img", "images/blank.png");
       FigureImage figureImage4_6 = new FigureImage("cell4_6", "cell4_6_img", "images/blank.png");
       FigureImage figureImage4_7 = new FigureImage("cell4_7", "cell4_7_img", "images/blank.png");
       FigureImage figureImage4_8 = new FigureImage("cell4_8", "cell4_8_img", "images/blank.png");
       FigureImage figureImage4_9 = new FigureImage("cell4_9", "cell4_9_img", "images/blank.png");
       FigureImage figureImage4_10 = new FigureImage("cell4_10", "cell4_10_img", "images/blank.png");
       FigureImage figureImage4_11 = new FigureImage("cell4_11", "cell4_11_img", "images/blank.png");
       FigureImage figureImage4_12 = new FigureImage("cell4_12", "cell4_12_img", "images/blank.png");
       FigureImage figureImage4_13 = new FigureImage("cell4_13", "cell4_13_img", "images/blank.png");
       FigureImage figureImage4_14 = new FigureImage("cell4_14", "cell4_14_img", "images/blank.png");
       FigureImage figureImage4_15 = new FigureImage("cell4_15", "cell4_15_img", "images/blank.png");
       FigureImage figureImage4_16 = new FigureImage("cell4_16", "cell4_16_img", "images/blank.png");
       FigureImage figureImage4_17 = new FigureImage("cell4_17", "cell4_17_img", "images/blank.png");
       FigureImage figureImage4_18 = new FigureImage("cell4_18", "cell4_18_img", "images/blank.png");
       FigureImage figureImage4_19 = new FigureImage("cell4_19", "cell4_19_img", "images/blank.png");
       FigureImage figureImage4_20 = new FigureImage("cell4_20", "cell4_20_img", "images/blank.png");
       FigureImage figureImage4_21 = new FigureImage("cell4_21", "cell4_21_img", "images/blank.png");
       FigureImage figureImage4_22 = new FigureImage("cell4_22", "cell4_22_img", "images/blank.png");
       FigureImage figureImage4_23 = new FigureImage("cell4_23", "cell4_23_img", "images/blank.png");
       FigureImage figureImage4_24 = new FigureImage("cell4_24", "cell4_24_img", "images/blank.png");
       // 5 ROW
        FigureImage figureImage5_1 = new FigureImage("cell5_1", "cell5_1_img", "images/blank.png");
       FigureImage figureImage5_2 = new FigureImage("cell5_2", "cell5_2_img", "images/blank.png");
       FigureImage figureImage5_3 = new FigureImage("cell5_3", "cell5_3_img", "images/blank.png");
       FigureImage figureImage5_4 = new FigureImage("cell5_4", "cell5_4_img", "images/blank.png");
       FigureImage figureImage5_5 = new FigureImage("cell5_5", "cell5_5_img", "images/blank.png");
       FigureImage figureImage5_6 = new FigureImage("cell5_6", "cell5_6_img", "images/blank.png");
       FigureImage figureImage5_7 = new FigureImage("cell5_7", "cell5_7_img", "images/blank.png");
       FigureImage figureImage5_8 = new FigureImage("cell5_8", "cell5_8_img", "images/blank.png");
       FigureImage figureImage5_9 = new FigureImage("cell5_9", "cell5_9_img", "images/blank.png");
       FigureImage figureImage5_10 = new FigureImage("cell5_10", "cell5_10_img", "images/blank.png");
       FigureImage figureImage5_11 = new FigureImage("cell5_11", "cell5_11_img", "images/blank.png");
       FigureImage figureImage5_12 = new FigureImage("cell5_12", "cell5_12_img", "images/blank.png");
       FigureImage figureImage5_13 = new FigureImage("cell5_13", "cell5_13_img", "images/blank.png");
       FigureImage figureImage5_14 = new FigureImage("cell5_14", "cell5_14_img", "images/blank.png");
       FigureImage figureImage5_15 = new FigureImage("cell5_15", "cell5_15_img", "images/blank.png");
       FigureImage figureImage5_16 = new FigureImage("cell5_16", "cell5_16_img", "images/blank.png");
       FigureImage figureImage5_17 = new FigureImage("cell5_17", "cell5_17_img", "images/blank.png");
       FigureImage figureImage5_18 = new FigureImage("cell5_18", "cell5_18_img", "images/blank.png");
       FigureImage figureImage5_19 = new FigureImage("cell5_19", "cell5_19_img", "images/blank.png");
       FigureImage figureImage5_20 = new FigureImage("cell5_20", "cell5_20_img", "images/blank.png");
       FigureImage figureImage5_21 = new FigureImage("cell5_21", "cell5_21_img", "images/blank.png");
       FigureImage figureImage5_22 = new FigureImage("cell5_22", "cell5_22_img", "images/blank.png");
       FigureImage figureImage5_23 = new FigureImage("cell5_23", "cell5_23_img", "images/blank.png");
       FigureImage figureImage5_24 = new FigureImage("cell5_24", "cell5_24_img", "images/blank.png");
       // 6 ROW
        FigureImage figureImage6_1 = new FigureImage("cell6_1", "cell6_1_img", "images/blank.png");
       FigureImage figureImage6_2 = new FigureImage("cell6_2", "cell6_2_img", "images/blank.png");
       FigureImage figureImage6_3 = new FigureImage("cell6_3", "cell6_3_img", "images/blank.png");
       FigureImage figureImage6_4 = new FigureImage("cell6_4", "cell6_4_img", "images/blank.png");
       FigureImage figureImage6_5 = new FigureImage("cell6_5", "cell6_5_img", "images/blank.png");
       FigureImage figureImage6_6 = new FigureImage("cell6_6", "cell6_6_img", "images/blank.png");
       FigureImage figureImage6_7 = new FigureImage("cell6_7", "cell6_7_img", "images/blank.png");
       FigureImage figureImage6_8 = new FigureImage("cell6_8", "cell6_8_img", "images/blank.png");
       FigureImage figureImage6_9 = new FigureImage("cell6_9", "cell6_9_img", "images/blank.png");
       FigureImage figureImage6_10 = new FigureImage("cell6_10", "cell6_10_img", "images/blank.png");
       FigureImage figureImage6_11 = new FigureImage("cell6_11", "cell6_11_img", "images/blank.png");
       FigureImage figureImage6_12 = new FigureImage("cell6_12", "cell6_12_img", "images/blank.png");
       FigureImage figureImage6_13 = new FigureImage("cell6_13", "cell6_13_img", "images/blank.png");
       FigureImage figureImage6_14 = new FigureImage("cell6_14", "cell6_14_img", "images/blank.png");
       FigureImage figureImage6_15 = new FigureImage("cell6_15", "cell6_15_img", "images/blank.png");
       FigureImage figureImage6_16 = new FigureImage("cell6_16", "cell6_16_img", "images/blank.png");
       FigureImage figureImage6_17 = new FigureImage("cell6_17", "cell6_17_img", "images/blank.png");
       FigureImage figureImage6_18 = new FigureImage("cell6_18", "cell6_18_img", "images/blank.png");
       FigureImage figureImage6_19 = new FigureImage("cell6_19", "cell6_19_img", "images/blank.png");
       FigureImage figureImage6_20 = new FigureImage("cell6_20", "cell6_20_img", "images/blank.png");
       FigureImage figureImage6_21 = new FigureImage("cell6_21", "cell6_21_img", "images/blank.png");
       FigureImage figureImage6_22 = new FigureImage("cell6_22", "cell6_22_img", "images/blank.png");
       FigureImage figureImage6_23 = new FigureImage("cell6_23", "cell6_23_img", "images/blank.png");
       FigureImage figureImage6_24 = new FigureImage("cell6_24", "cell6_24_img", "images/blank.png");
       // 7 ROW
       FigureImage figureImage7_1 = new FigureImage("cell7_1", "cell7_1_img", "images/blank.png");
       FigureImage figureImage7_2 = new FigureImage("cell7_2", "cell7_2_img", "images/blank.png");
       FigureImage figureImage7_3 = new FigureImage("cell7_3", "cell7_3_img", "images/blank.png");
       FigureImage figureImage7_4 = new FigureImage("cell7_4", "cell7_4_img", "images/blank.png");
       FigureImage figureImage7_5 = new FigureImage("cell7_5", "cell7_5_img", "images/blank.png");
       FigureImage figureImage7_6 = new FigureImage("cell7_6", "cell7_6_img", "images/blank.png");
       FigureImage figureImage7_7 = new FigureImage("cell7_7", "cell7_7_img", "images/blank.png");
       FigureImage figureImage7_8 = new FigureImage("cell7_8", "cell7_8_img", "images/blank.png");
       FigureImage figureImage7_9 = new FigureImage("cell7_9", "cell7_9_img", "images/blank.png");
       FigureImage figureImage7_10 = new FigureImage("cell7_10", "cell7_10_img", "images/blank.png");
       FigureImage figureImage7_11 = new FigureImage("cell7_11", "cell7_11_img", "images/blank.png");
       FigureImage figureImage7_12 = new FigureImage("cell7_12", "cell7_12_img", "images/blank.png");
       FigureImage figureImage7_13 = new FigureImage("cell7_13", "cell7_13_img", "images/blank.png");
       FigureImage figureImage7_14 = new FigureImage("cell7_14", "cell7_14_img", "images/blank.png");
       FigureImage figureImage7_15 = new FigureImage("cell7_15", "cell7_15_img", "images/blank.png");
       FigureImage figureImage7_16 = new FigureImage("cell7_16", "cell7_16_img", "images/blank.png");
       FigureImage figureImage7_17 = new FigureImage("cell7_17", "cell7_17_img", "images/blank.png");
       FigureImage figureImage7_18 = new FigureImage("cell7_18", "cell7_18_img", "images/blank.png");
       FigureImage figureImage7_19 = new FigureImage("cell7_19", "cell7_19_img", "images/blank.png");
       FigureImage figureImage7_20 = new FigureImage("cell7_20", "cell7_20_img", "images/blank.png");
       FigureImage figureImage7_21 = new FigureImage("cell7_21", "cell7_21_img", "images/blank.png");
       FigureImage figureImage7_22 = new FigureImage("cell7_22", "cell7_22_img", "images/blank.png");
       FigureImage figureImage7_23 = new FigureImage("cell7_23", "cell7_23_img", "images/blank.png");
       FigureImage figureImage7_24 = new FigureImage("cell7_24", "cell7_24_img", "images/blank.png");
       // 8 ROW
       FigureImage figureImage8_1 = new FigureImage("cell8_1", "cell8_1_img", "images/blank.png");
       FigureImage figureImage8_2 = new FigureImage("cell8_2", "cell8_2_img", "images/blank.png");
       FigureImage figureImage8_3 = new FigureImage("cell8_3", "cell8_3_img", "images/blank.png");
       FigureImage figureImage8_4 = new FigureImage("cell8_4", "cell8_4_img", "images/blank.png");
       FigureImage figureImage8_5 = new FigureImage("cell8_5", "cell8_5_img", "images/blank.png");
       FigureImage figureImage8_6 = new FigureImage("cell8_6", "cell8_6_img", "images/blank.png");
       FigureImage figureImage8_7 = new FigureImage("cell8_7", "cell8_7_img", "images/blank.png");
       FigureImage figureImage8_8 = new FigureImage("cell8_8", "cell8_8_img", "images/blank.png");
       FigureImage figureImage8_9 = new FigureImage("cell8_9", "cell8_9_img", "images/blank.png");
       FigureImage figureImage8_10 = new FigureImage("cell8_10", "cell8_10_img", "images/blank.png");
       FigureImage figureImage8_11 = new FigureImage("cell8_11", "cell8_11_img", "images/blank.png");
       FigureImage figureImage8_12 = new FigureImage("cell8_12", "cell8_12_img", "images/blank.png");
       FigureImage figureImage8_13 = new FigureImage("cell8_13", "cell8_13_img", "images/blank.png");
       FigureImage figureImage8_14 = new FigureImage("cell8_14", "cell8_14_img", "images/blank.png");
       FigureImage figureImage8_15 = new FigureImage("cell8_15", "cell8_15_img", "images/blank.png");
       FigureImage figureImage8_16 = new FigureImage("cell8_16", "cell8_16_img", "images/blank.png");
       FigureImage figureImage8_17 = new FigureImage("cell8_17", "cell8_17_img", "images/blank.png");
       FigureImage figureImage8_18 = new FigureImage("cell8_18", "cell8_18_img", "images/blank.png");
       FigureImage figureImage8_19 = new FigureImage("cell8_19", "cell8_19_img", "images/blank.png");
       FigureImage figureImage8_20 = new FigureImage("cell8_20", "cell8_20_img", "images/blank.png");
       FigureImage figureImage8_21 = new FigureImage("cell8_21", "cell8_21_img", "images/blank.png");
       FigureImage figureImage8_22 = new FigureImage("cell8_22", "cell8_22_img", "images/blank.png");
       FigureImage figureImage8_23 = new FigureImage("cell8_23", "cell8_23_img", "images/blank.png");
       FigureImage figureImage8_24 = new FigureImage("cell8_24", "cell8_24_img", "images/blank.png");
       // 9 ROW
        FigureImage figureImage9_1 = new FigureImage("cell9_1", "cell9_1_img", "images/spearman.png");
       FigureImage figureImage9_2 = new FigureImage("cell9_2", "cell9_2_img", "images/spearman.png");
       FigureImage figureImage9_3 = new FigureImage("cell9_3", "cell9_3_img", "images/spearman.png");
       FigureImage figureImage9_4 = new FigureImage("cell9_4", "cell9_4_img", "images/spearman.png");
       FigureImage figureImage9_5 = new FigureImage("cell9_5", "cell9_5_img", "images/spearman.png");
       FigureImage figureImage9_6 = new FigureImage("cell9_6", "cell9_6_img", "images/spearman.png");
       FigureImage figureImage9_7 = new FigureImage("cell9_7", "cell9_7_img", "images/spearman.png");
       FigureImage figureImage9_8 = new FigureImage("cell9_8", "cell9_8_img", "images/spearman.png");
       FigureImage figureImage9_9 = new FigureImage("cell9_9", "cell9_9_img", "images/blank.png");
       FigureImage figureImage9_10 = new FigureImage("cell9_10", "cell9_10_img", "images/spearman.png");
       FigureImage figureImage9_11 = new FigureImage("cell9_11", "cell9_11_img", "images/spearman.png");
       FigureImage figureImage9_12 = new FigureImage("cell9_12", "cell9_12_img", "images/spearman.png");
       FigureImage figureImage9_13 = new FigureImage("cell9_13", "cell9_13_img", "images/spearman.png");
       FigureImage figureImage9_14 = new FigureImage("cell9_14", "cell9_14_img", "images/spearman.png");
       FigureImage figureImage9_15 = new FigureImage("cell9_15", "cell9_15_img", "images/spearman.png");
       FigureImage figureImage9_16 = new FigureImage("cell9_16", "cell9_16_img", "images/blank.png");
       FigureImage figureImage9_17 = new FigureImage("cell9_17", "cell9_17_img", "images/spearman.png");
       FigureImage figureImage9_18 = new FigureImage("cell9_18", "cell9_18_img", "images/spearman.png");
       FigureImage figureImage9_19 = new FigureImage("cell9_19", "cell9_19_img", "images/spearman.png");
       FigureImage figureImage9_20 = new FigureImage("cell9_20", "cell9_20_img", "images/tank_head.png");
       FigureImage figureImage9_21 = new FigureImage("cell9_21", "cell9_21_img", "images/spearman.png");
       FigureImage figureImage9_22 = new FigureImage("cell9_22", "cell9_22_img", "images/spearman.png");
       FigureImage figureImage9_23 = new FigureImage("cell9_23", "cell9_23_img", "images/spearman.png");
       FigureImage figureImage9_24 = new FigureImage("cell9_24", "cell9_24_img", "images/spearman.png");
       // 10 ROW
       FigureImage figureImage10_1 = new FigureImage("cell10_1", "cell10_1_img", "images/wizard.png");
       FigureImage figureImage10_2 = new FigureImage("cell10_2", "cell10_2_img", "images/demigriph.png");
       FigureImage figureImage10_3 = new FigureImage("cell10_3", "cell10_3_img", "images/cavalry.png");
       FigureImage figureImage10_4 = new FigureImage("cell10_4", "cell10_4_img", "images/griffin.png");
       FigureImage figureImage10_5 = new FigureImage("cell10_5", "cell10_5_img", "images/cavalry.png");
       FigureImage figureImage10_6 = new FigureImage("cell10_6", "cell10_6_img", "images/griffin.png");
       FigureImage figureImage10_7 = new FigureImage("cell10_7", "cell10_7_img", "images/cavalry.png");
       FigureImage figureImage10_8 = new FigureImage("cell10_8", "cell10_8_img", "images/witchhunter.png");
       FigureImage figureImage10_9 = new FigureImage("cell10_9", "cell10_9_img", "images/blank.png");
       FigureImage figureImage10_10 = new FigureImage("cell10_10", "cell10_10_img", "images/oficer.png");
       FigureImage figureImage10_11 = new FigureImage("cell10_11", "cell10_11_img", "images/demigriph.png");
       FigureImage figureImage10_12 = new FigureImage("cell10_12", "cell10_12_img", "images/king.png");
       FigureImage figureImage10_13 = new FigureImage("cell10_13", "cell10_13_img", "images/demigriph.png");
       FigureImage figureImage10_14 = new FigureImage("cell10_14", "cell10_14_img", "images/wizard.png");
       FigureImage figureImage10_15 = new FigureImage("cell10_15", "cell10_15_img", "images/oficer.png");
       FigureImage figureImage10_16 = new FigureImage("cell10_16", "cell10_16_img", "images/blank.png");
       FigureImage figureImage10_17 = new FigureImage("cell10_17", "cell10_17_img", "images/spearman.png");
       FigureImage figureImage10_18 = new FigureImage("cell10_18", "cell10_18_img", "images/wizard.png");
       FigureImage figureImage10_19 = new FigureImage("cell10_19", "cell10_19_img", "images/witchhunter.png");
       FigureImage figureImage10_20 = new FigureImage("cell10_20", "cell10_20_img", "images/tank_back.png");
       FigureImage figureImage10_21 = new FigureImage("cell10_21", "cell10_21_img", "images/witchhunter.png");
       FigureImage figureImage10_22 = new FigureImage("cell10_22", "cell10_22_img", "images/wizard.png");
       FigureImage figureImage10_23 = new FigureImage("cell10_23", "cell10_23_img", "images/griffin.png");
       FigureImage figureImage10_24 = new FigureImage("cell10_24", "cell10_24_img", "images/griffin.png");


        // ADDITING IMAGES TO ARRAY 1 ROW
        chessMoves.addFigure(figureImage1_1);
        chessMoves.addFigure(figureImage1_2);
        chessMoves.addFigure(figureImage1_3);
        chessMoves.addFigure(figureImage1_4);
        chessMoves.addFigure(figureImage1_5);
        chessMoves.addFigure(figureImage1_6);
       chessMoves.addFigure(figureImage1_7);
       chessMoves.addFigure(figureImage1_8);
       chessMoves.addFigure(figureImage1_9);
       chessMoves.addFigure(figureImage1_10);
       chessMoves.addFigure(figureImage1_11);
       chessMoves.addFigure(figureImage1_12);
       chessMoves.addFigure(figureImage1_13);
       chessMoves.addFigure(figureImage1_14);
       chessMoves.addFigure(figureImage1_15);
       chessMoves.addFigure(figureImage1_16);
       chessMoves.addFigure(figureImage1_17);
       chessMoves.addFigure(figureImage1_18);
       chessMoves.addFigure(figureImage1_19);
       chessMoves.addFigure(figureImage1_20);
       chessMoves.addFigure(figureImage1_21);
       chessMoves.addFigure(figureImage1_22);
       chessMoves.addFigure(figureImage1_23);
       chessMoves.addFigure(figureImage1_24);
       // 2 ROW
       chessMoves.addFigure(figureImage2_1);
       chessMoves.addFigure(figureImage2_2);
       chessMoves.addFigure(figureImage2_3);
       chessMoves.addFigure(figureImage2_4);
       chessMoves.addFigure(figureImage2_5);
       chessMoves.addFigure(figureImage2_6);
       chessMoves.addFigure(figureImage2_7);
       chessMoves.addFigure(figureImage2_8);
       chessMoves.addFigure(figureImage2_9);
       chessMoves.addFigure(figureImage2_10);
       chessMoves.addFigure(figureImage2_11);
       chessMoves.addFigure(figureImage2_12);
       chessMoves.addFigure(figureImage2_13);
       chessMoves.addFigure(figureImage2_14);
       chessMoves.addFigure(figureImage2_15);
       chessMoves.addFigure(figureImage2_16);
       chessMoves.addFigure(figureImage2_17);
       chessMoves.addFigure(figureImage2_18);
       chessMoves.addFigure(figureImage2_19);
       chessMoves.addFigure(figureImage2_20);
       chessMoves.addFigure(figureImage2_21);
       chessMoves.addFigure(figureImage2_22);
       chessMoves.addFigure(figureImage2_23);
       chessMoves.addFigure(figureImage2_24);
       // 3 ROW
       chessMoves.addFigure(figureImage3_1);
       chessMoves.addFigure(figureImage3_2);
       chessMoves.addFigure(figureImage3_3);
       chessMoves.addFigure(figureImage3_4);
       chessMoves.addFigure(figureImage3_5);
       chessMoves.addFigure(figureImage3_6);
       chessMoves.addFigure(figureImage3_7);
       chessMoves.addFigure(figureImage3_8);
       chessMoves.addFigure(figureImage3_9);
       chessMoves.addFigure(figureImage3_10);
       chessMoves.addFigure(figureImage3_11);
       chessMoves.addFigure(figureImage3_12);
       chessMoves.addFigure(figureImage3_13);
       chessMoves.addFigure(figureImage3_14);
       chessMoves.addFigure(figureImage3_15);
       chessMoves.addFigure(figureImage3_16);
       chessMoves.addFigure(figureImage3_17);
       chessMoves.addFigure(figureImage3_18);
       chessMoves.addFigure(figureImage3_19);
       chessMoves.addFigure(figureImage3_20);
       chessMoves.addFigure(figureImage3_21);
       chessMoves.addFigure(figureImage3_22);
       chessMoves.addFigure(figureImage3_23);
       chessMoves.addFigure(figureImage3_24);
       // 4 ROW
       chessMoves.addFigure(figureImage4_1);
       chessMoves.addFigure(figureImage4_2);
       chessMoves.addFigure(figureImage4_3);
       chessMoves.addFigure(figureImage4_4);
       chessMoves.addFigure(figureImage4_5);
       chessMoves.addFigure(figureImage4_6);
       chessMoves.addFigure(figureImage4_7);
       chessMoves.addFigure(figureImage4_8);
       chessMoves.addFigure(figureImage4_9);
       chessMoves.addFigure(figureImage4_10);
       chessMoves.addFigure(figureImage4_11);
       chessMoves.addFigure(figureImage4_12);
       chessMoves.addFigure(figureImage4_13);
       chessMoves.addFigure(figureImage4_14);
       chessMoves.addFigure(figureImage4_15);
       chessMoves.addFigure(figureImage4_16);
       chessMoves.addFigure(figureImage4_17);
       chessMoves.addFigure(figureImage4_18);
       chessMoves.addFigure(figureImage4_19);
       chessMoves.addFigure(figureImage4_20);
       chessMoves.addFigure(figureImage4_21);
       chessMoves.addFigure(figureImage4_22);
       chessMoves.addFigure(figureImage4_23);
       chessMoves.addFigure(figureImage4_24);
       // 5 ROW
       chessMoves.addFigure(figureImage5_1);
       chessMoves.addFigure(figureImage5_2);
       chessMoves.addFigure(figureImage5_3);
       chessMoves.addFigure(figureImage5_4);
       chessMoves.addFigure(figureImage5_5);
       chessMoves.addFigure(figureImage5_6);
       chessMoves.addFigure(figureImage5_7);
       chessMoves.addFigure(figureImage5_8);
       chessMoves.addFigure(figureImage5_9);
       chessMoves.addFigure(figureImage5_10);
       chessMoves.addFigure(figureImage5_11);
       chessMoves.addFigure(figureImage5_12);
       chessMoves.addFigure(figureImage5_13);
       chessMoves.addFigure(figureImage5_14);
       chessMoves.addFigure(figureImage5_15);
       chessMoves.addFigure(figureImage5_16);
       chessMoves.addFigure(figureImage5_17);
       chessMoves.addFigure(figureImage5_18);
       chessMoves.addFigure(figureImage5_19);
       chessMoves.addFigure(figureImage5_20);
       chessMoves.addFigure(figureImage5_21);
       chessMoves.addFigure(figureImage5_22);
       chessMoves.addFigure(figureImage5_23);
       chessMoves.addFigure(figureImage5_24);
       // 6 ROW
       chessMoves.addFigure(figureImage6_1);
       chessMoves.addFigure(figureImage6_2);
       chessMoves.addFigure(figureImage6_3);
       chessMoves.addFigure(figureImage6_4);
       chessMoves.addFigure(figureImage6_5);
       chessMoves.addFigure(figureImage6_6);
       chessMoves.addFigure(figureImage6_7);
       chessMoves.addFigure(figureImage6_8);
       chessMoves.addFigure(figureImage6_9);
       chessMoves.addFigure(figureImage6_10);
       chessMoves.addFigure(figureImage6_11);
       chessMoves.addFigure(figureImage6_12);
       chessMoves.addFigure(figureImage6_13);
       chessMoves.addFigure(figureImage6_14);
       chessMoves.addFigure(figureImage6_15);
       chessMoves.addFigure(figureImage6_16);
       chessMoves.addFigure(figureImage6_17);
       chessMoves.addFigure(figureImage6_18);
       chessMoves.addFigure(figureImage6_19);
       chessMoves.addFigure(figureImage6_20);
       chessMoves.addFigure(figureImage6_21);
       chessMoves.addFigure(figureImage6_22);
       chessMoves.addFigure(figureImage6_23);
       chessMoves.addFigure(figureImage6_24);
       // 7 ROW
       chessMoves.addFigure(figureImage7_1);
       chessMoves.addFigure(figureImage7_2);
       chessMoves.addFigure(figureImage7_3);
       chessMoves.addFigure(figureImage7_4);
       chessMoves.addFigure(figureImage7_5);
       chessMoves.addFigure(figureImage7_6);
       chessMoves.addFigure(figureImage7_7);
       chessMoves.addFigure(figureImage7_8);
       chessMoves.addFigure(figureImage7_9);
       chessMoves.addFigure(figureImage7_10);
       chessMoves.addFigure(figureImage7_11);
       chessMoves.addFigure(figureImage7_12);
       chessMoves.addFigure(figureImage7_13);
       chessMoves.addFigure(figureImage7_14);
       chessMoves.addFigure(figureImage7_15);
       chessMoves.addFigure(figureImage7_16);
       chessMoves.addFigure(figureImage7_17);
       chessMoves.addFigure(figureImage7_18);
       chessMoves.addFigure(figureImage7_19);
       chessMoves.addFigure(figureImage7_20);
       chessMoves.addFigure(figureImage7_21);
       chessMoves.addFigure(figureImage7_22);
       chessMoves.addFigure(figureImage7_23);
       chessMoves.addFigure(figureImage7_24);
       // 8 ROW
       chessMoves.addFigure(figureImage8_1);
       chessMoves.addFigure(figureImage8_2);
       chessMoves.addFigure(figureImage8_3);
       chessMoves.addFigure(figureImage8_4);
       chessMoves.addFigure(figureImage8_5);
       chessMoves.addFigure(figureImage8_6);
       chessMoves.addFigure(figureImage8_7);
       chessMoves.addFigure(figureImage8_8);
       chessMoves.addFigure(figureImage8_9);
       chessMoves.addFigure(figureImage8_10);
       chessMoves.addFigure(figureImage8_11);
       chessMoves.addFigure(figureImage8_12);
       chessMoves.addFigure(figureImage8_13);
       chessMoves.addFigure(figureImage8_14);
       chessMoves.addFigure(figureImage8_15);
       chessMoves.addFigure(figureImage8_16);
       chessMoves.addFigure(figureImage8_17);
       chessMoves.addFigure(figureImage8_18);
       chessMoves.addFigure(figureImage8_19);
       chessMoves.addFigure(figureImage8_20);
       chessMoves.addFigure(figureImage8_21);
       chessMoves.addFigure(figureImage8_22);
       chessMoves.addFigure(figureImage8_23);
       chessMoves.addFigure(figureImage8_24);
       // 9 ROW
       chessMoves.addFigure(figureImage9_1);
       chessMoves.addFigure(figureImage9_2);
       chessMoves.addFigure(figureImage9_3);
       chessMoves.addFigure(figureImage9_4);
       chessMoves.addFigure(figureImage9_5);
       chessMoves.addFigure(figureImage9_6);
       chessMoves.addFigure(figureImage9_7);
       chessMoves.addFigure(figureImage9_8);
       chessMoves.addFigure(figureImage9_9);
       chessMoves.addFigure(figureImage9_10);
       chessMoves.addFigure(figureImage9_11);
       chessMoves.addFigure(figureImage9_12);
       chessMoves.addFigure(figureImage9_13);
       chessMoves.addFigure(figureImage9_14);
       chessMoves.addFigure(figureImage9_15);
       chessMoves.addFigure(figureImage9_16);
       chessMoves.addFigure(figureImage9_17);
       chessMoves.addFigure(figureImage9_18);
       chessMoves.addFigure(figureImage9_19);
       chessMoves.addFigure(figureImage9_20);
       chessMoves.addFigure(figureImage9_21);
       chessMoves.addFigure(figureImage9_22);
       chessMoves.addFigure(figureImage9_23);
       chessMoves.addFigure(figureImage9_24);
       // 10 ROW
       chessMoves.addFigure(figureImage10_1);
       chessMoves.addFigure(figureImage10_2);
       chessMoves.addFigure(figureImage10_3);
       chessMoves.addFigure(figureImage10_4);
       chessMoves.addFigure(figureImage10_5);
       chessMoves.addFigure(figureImage10_6);
       chessMoves.addFigure(figureImage10_7);
       chessMoves.addFigure(figureImage10_8);
       chessMoves.addFigure(figureImage10_9);
       chessMoves.addFigure(figureImage10_10);
       chessMoves.addFigure(figureImage10_11);
       chessMoves.addFigure(figureImage10_12);
       chessMoves.addFigure(figureImage10_13);
       chessMoves.addFigure(figureImage10_14);
       chessMoves.addFigure(figureImage10_15);
       chessMoves.addFigure(figureImage10_16);
       chessMoves.addFigure(figureImage10_17);
       chessMoves.addFigure(figureImage10_18);
       chessMoves.addFigure(figureImage10_19);
       chessMoves.addFigure(figureImage10_20);
       chessMoves.addFigure(figureImage10_21);
       chessMoves.addFigure(figureImage10_22);
       chessMoves.addFigure(figureImage10_23);
       chessMoves.addFigure(figureImage10_24);




        session.setAttribute("chessMoves", chessMoves);


        // ADDING TO MODEL 1 ROW
       model.addAttribute(figureImage1_1.getImageName(), figureImage1_1.getPath());
       model.addAttribute(figureImage1_2.getImageName(), figureImage1_2.getPath());
       model.addAttribute(figureImage1_3.getImageName(), figureImage1_3.getPath());
       model.addAttribute(figureImage1_4.getImageName(), figureImage1_4.getPath());
       model.addAttribute(figureImage1_5.getImageName(), figureImage1_5.getPath());
       model.addAttribute(figureImage1_6.getImageName(), figureImage1_6.getPath());
       model.addAttribute(figureImage1_7.getImageName(), figureImage1_7.getPath());
       model.addAttribute(figureImage1_8.getImageName(), figureImage1_8.getPath());
       model.addAttribute(figureImage1_9.getImageName(), figureImage1_9.getPath());
       model.addAttribute(figureImage1_10.getImageName(), figureImage1_10.getPath());
       model.addAttribute(figureImage1_11.getImageName(), figureImage1_11.getPath());
       model.addAttribute(figureImage1_12.getImageName(), figureImage1_12.getPath());
       model.addAttribute(figureImage1_13.getImageName(), figureImage1_13.getPath());
       model.addAttribute(figureImage1_14.getImageName(), figureImage1_14.getPath());
       model.addAttribute(figureImage1_15.getImageName(), figureImage1_15.getPath());
       model.addAttribute(figureImage1_16.getImageName(), figureImage1_16.getPath());
       model.addAttribute(figureImage1_17.getImageName(), figureImage1_17.getPath());
       model.addAttribute(figureImage1_18.getImageName(), figureImage1_18.getPath());
       model.addAttribute(figureImage1_19.getImageName(), figureImage1_19.getPath());
       model.addAttribute(figureImage1_20.getImageName(), figureImage1_20.getPath());
       model.addAttribute(figureImage1_21.getImageName(), figureImage1_21.getPath());
       model.addAttribute(figureImage1_22.getImageName(), figureImage1_22.getPath());
       model.addAttribute(figureImage1_23.getImageName(), figureImage1_23.getPath());
       model.addAttribute(figureImage1_24.getImageName(), figureImage1_24.getPath());
        // 2 ROW
       model.addAttribute(figureImage2_1.getImageName(), figureImage2_1.getPath());
       model.addAttribute(figureImage2_2.getImageName(), figureImage2_2.getPath());
       model.addAttribute(figureImage2_3.getImageName(), figureImage2_3.getPath());
       model.addAttribute(figureImage2_4.getImageName(), figureImage2_4.getPath());
       model.addAttribute(figureImage2_5.getImageName(), figureImage2_5.getPath());
       model.addAttribute(figureImage2_6.getImageName(), figureImage2_6.getPath());
       model.addAttribute(figureImage2_7.getImageName(), figureImage2_7.getPath());
       model.addAttribute(figureImage2_8.getImageName(), figureImage2_8.getPath());
       model.addAttribute(figureImage2_9.getImageName(), figureImage2_9.getPath());
       model.addAttribute(figureImage2_10.getImageName(), figureImage2_10.getPath());
       model.addAttribute(figureImage2_11.getImageName(), figureImage2_11.getPath());
       model.addAttribute(figureImage2_12.getImageName(), figureImage2_12.getPath());
       model.addAttribute(figureImage2_13.getImageName(), figureImage2_13.getPath());
       model.addAttribute(figureImage2_14.getImageName(), figureImage2_14.getPath());
       model.addAttribute(figureImage2_15.getImageName(), figureImage2_15.getPath());
       model.addAttribute(figureImage2_16.getImageName(), figureImage2_16.getPath());
       model.addAttribute(figureImage2_17.getImageName(), figureImage2_17.getPath());
       model.addAttribute(figureImage2_18.getImageName(), figureImage2_18.getPath());
       model.addAttribute(figureImage2_19.getImageName(), figureImage2_19.getPath());
       model.addAttribute(figureImage2_20.getImageName(), figureImage2_20.getPath());
       model.addAttribute(figureImage2_21.getImageName(), figureImage2_21.getPath());
       model.addAttribute(figureImage2_22.getImageName(), figureImage2_22.getPath());
       model.addAttribute(figureImage2_23.getImageName(), figureImage2_23.getPath());
       model.addAttribute(figureImage2_24.getImageName(), figureImage2_24.getPath());
        // 3 ROW
       model.addAttribute(figureImage3_1.getImageName(), figureImage3_1.getPath());
       model.addAttribute(figureImage3_2.getImageName(), figureImage3_2.getPath());
       model.addAttribute(figureImage3_3.getImageName(), figureImage3_3.getPath());
       model.addAttribute(figureImage3_4.getImageName(), figureImage3_4.getPath());
       model.addAttribute(figureImage3_5.getImageName(), figureImage3_5.getPath());
       model.addAttribute(figureImage3_6.getImageName(), figureImage3_6.getPath());
       model.addAttribute(figureImage3_7.getImageName(), figureImage3_7.getPath());
       model.addAttribute(figureImage3_8.getImageName(), figureImage3_8.getPath());
       model.addAttribute(figureImage3_9.getImageName(), figureImage3_9.getPath());
       model.addAttribute(figureImage3_10.getImageName(), figureImage3_10.getPath());
       model.addAttribute(figureImage3_11.getImageName(), figureImage3_11.getPath());
       model.addAttribute(figureImage3_12.getImageName(), figureImage3_12.getPath());
       model.addAttribute(figureImage3_13.getImageName(), figureImage3_13.getPath());
       model.addAttribute(figureImage3_14.getImageName(), figureImage3_14.getPath());
       model.addAttribute(figureImage3_15.getImageName(), figureImage3_15.getPath());
       model.addAttribute(figureImage3_16.getImageName(), figureImage3_16.getPath());
       model.addAttribute(figureImage3_17.getImageName(), figureImage3_17.getPath());
       model.addAttribute(figureImage3_18.getImageName(), figureImage3_18.getPath());
       model.addAttribute(figureImage3_19.getImageName(), figureImage3_19.getPath());
       model.addAttribute(figureImage3_20.getImageName(), figureImage3_20.getPath());
       model.addAttribute(figureImage3_21.getImageName(), figureImage3_21.getPath());
       model.addAttribute(figureImage3_22.getImageName(), figureImage3_22.getPath());
       model.addAttribute(figureImage3_23.getImageName(), figureImage3_23.getPath());
       model.addAttribute(figureImage3_24.getImageName(), figureImage3_24.getPath());
       // 4 ROW
       model.addAttribute(figureImage4_1.getImageName(), figureImage4_1.getPath());
       model.addAttribute(figureImage4_2.getImageName(), figureImage4_2.getPath());
       model.addAttribute(figureImage4_3.getImageName(), figureImage4_3.getPath());
       model.addAttribute(figureImage4_4.getImageName(), figureImage4_4.getPath());
       model.addAttribute(figureImage4_5.getImageName(), figureImage4_5.getPath());
       model.addAttribute(figureImage4_6.getImageName(), figureImage4_6.getPath());
       model.addAttribute(figureImage4_7.getImageName(), figureImage4_7.getPath());
       model.addAttribute(figureImage4_8.getImageName(), figureImage4_8.getPath());
       model.addAttribute(figureImage4_9.getImageName(), figureImage4_9.getPath());
       model.addAttribute(figureImage4_10.getImageName(), figureImage4_10.getPath());
       model.addAttribute(figureImage4_11.getImageName(), figureImage4_11.getPath());
       model.addAttribute(figureImage4_12.getImageName(), figureImage4_12.getPath());
       model.addAttribute(figureImage4_13.getImageName(), figureImage4_13.getPath());
       model.addAttribute(figureImage4_14.getImageName(), figureImage4_14.getPath());
       model.addAttribute(figureImage4_15.getImageName(), figureImage4_15.getPath());
       model.addAttribute(figureImage4_16.getImageName(), figureImage4_16.getPath());
       model.addAttribute(figureImage4_17.getImageName(), figureImage4_17.getPath());
       model.addAttribute(figureImage4_18.getImageName(), figureImage4_18.getPath());
       model.addAttribute(figureImage4_19.getImageName(), figureImage4_19.getPath());
       model.addAttribute(figureImage4_20.getImageName(), figureImage4_20.getPath());
       model.addAttribute(figureImage4_21.getImageName(), figureImage4_21.getPath());
       model.addAttribute(figureImage4_22.getImageName(), figureImage4_22.getPath());
       model.addAttribute(figureImage4_23.getImageName(), figureImage4_23.getPath());
       model.addAttribute(figureImage4_24.getImageName(), figureImage4_24.getPath());
       // 5 ROW
       model.addAttribute(figureImage5_1.getImageName(), figureImage5_1.getPath());
       model.addAttribute(figureImage5_2.getImageName(), figureImage5_2.getPath());
       model.addAttribute(figureImage5_3.getImageName(), figureImage5_3.getPath());
       model.addAttribute(figureImage5_4.getImageName(), figureImage5_4.getPath());
       model.addAttribute(figureImage5_5.getImageName(), figureImage5_5.getPath());
       model.addAttribute(figureImage5_6.getImageName(), figureImage5_6.getPath());
       model.addAttribute(figureImage5_7.getImageName(), figureImage5_7.getPath());
       model.addAttribute(figureImage5_8.getImageName(), figureImage5_8.getPath());
       model.addAttribute(figureImage5_9.getImageName(), figureImage5_9.getPath());
       model.addAttribute(figureImage5_10.getImageName(), figureImage5_10.getPath());
       model.addAttribute(figureImage5_11.getImageName(), figureImage5_11.getPath());
       model.addAttribute(figureImage5_12.getImageName(), figureImage5_12.getPath());
       model.addAttribute(figureImage5_13.getImageName(), figureImage5_13.getPath());
       model.addAttribute(figureImage5_14.getImageName(), figureImage5_14.getPath());
       model.addAttribute(figureImage5_15.getImageName(), figureImage5_15.getPath());
       model.addAttribute(figureImage5_16.getImageName(), figureImage5_16.getPath());
       model.addAttribute(figureImage5_17.getImageName(), figureImage5_17.getPath());
       model.addAttribute(figureImage5_18.getImageName(), figureImage5_18.getPath());
       model.addAttribute(figureImage5_19.getImageName(), figureImage5_19.getPath());
       model.addAttribute(figureImage5_20.getImageName(), figureImage5_20.getPath());
       model.addAttribute(figureImage5_21.getImageName(), figureImage5_21.getPath());
       model.addAttribute(figureImage5_22.getImageName(), figureImage5_22.getPath());
       model.addAttribute(figureImage5_23.getImageName(), figureImage5_23.getPath());
       model.addAttribute(figureImage5_24.getImageName(), figureImage5_24.getPath());
       // 6 ROW
       model.addAttribute(figureImage6_1.getImageName(), figureImage6_1.getPath());
       model.addAttribute(figureImage6_2.getImageName(), figureImage6_2.getPath());
       model.addAttribute(figureImage6_3.getImageName(), figureImage6_3.getPath());
       model.addAttribute(figureImage6_4.getImageName(), figureImage6_4.getPath());
       model.addAttribute(figureImage6_5.getImageName(), figureImage6_5.getPath());
       model.addAttribute(figureImage6_6.getImageName(), figureImage6_6.getPath());
       model.addAttribute(figureImage6_7.getImageName(), figureImage6_7.getPath());
       model.addAttribute(figureImage6_8.getImageName(), figureImage6_8.getPath());
       model.addAttribute(figureImage6_9.getImageName(), figureImage6_9.getPath());
       model.addAttribute(figureImage6_10.getImageName(), figureImage6_10.getPath());
       model.addAttribute(figureImage6_11.getImageName(), figureImage6_11.getPath());
       model.addAttribute(figureImage6_12.getImageName(), figureImage6_12.getPath());
       model.addAttribute(figureImage6_13.getImageName(), figureImage6_13.getPath());
       model.addAttribute(figureImage6_14.getImageName(), figureImage6_14.getPath());
       model.addAttribute(figureImage6_15.getImageName(), figureImage6_15.getPath());
       model.addAttribute(figureImage6_16.getImageName(), figureImage6_16.getPath());
       model.addAttribute(figureImage6_17.getImageName(), figureImage6_17.getPath());
       model.addAttribute(figureImage6_18.getImageName(), figureImage6_18.getPath());
       model.addAttribute(figureImage6_19.getImageName(), figureImage6_19.getPath());
       model.addAttribute(figureImage6_20.getImageName(), figureImage6_20.getPath());
       model.addAttribute(figureImage6_21.getImageName(), figureImage6_21.getPath());
       model.addAttribute(figureImage6_22.getImageName(), figureImage6_22.getPath());
       model.addAttribute(figureImage6_23.getImageName(), figureImage6_23.getPath());
       model.addAttribute(figureImage6_24.getImageName(), figureImage6_24.getPath());
       // 7 ROW
       model.addAttribute(figureImage7_1.getImageName(), figureImage7_1.getPath());
       model.addAttribute(figureImage7_2.getImageName(), figureImage7_2.getPath());
       model.addAttribute(figureImage7_3.getImageName(), figureImage7_3.getPath());
       model.addAttribute(figureImage7_4.getImageName(), figureImage7_4.getPath());
       model.addAttribute(figureImage7_5.getImageName(), figureImage7_5.getPath());
       model.addAttribute(figureImage7_6.getImageName(), figureImage7_6.getPath());
       model.addAttribute(figureImage7_7.getImageName(), figureImage7_7.getPath());
       model.addAttribute(figureImage7_8.getImageName(), figureImage7_8.getPath());
       model.addAttribute(figureImage7_9.getImageName(), figureImage7_9.getPath());
       model.addAttribute(figureImage7_10.getImageName(), figureImage7_10.getPath());
       model.addAttribute(figureImage7_11.getImageName(), figureImage7_11.getPath());
       model.addAttribute(figureImage7_12.getImageName(), figureImage7_12.getPath());
       model.addAttribute(figureImage7_13.getImageName(), figureImage7_13.getPath());
       model.addAttribute(figureImage7_14.getImageName(), figureImage7_14.getPath());
       model.addAttribute(figureImage7_15.getImageName(), figureImage7_15.getPath());
       model.addAttribute(figureImage7_16.getImageName(), figureImage7_16.getPath());
       model.addAttribute(figureImage7_17.getImageName(), figureImage7_17.getPath());
       model.addAttribute(figureImage7_18.getImageName(), figureImage7_18.getPath());
       model.addAttribute(figureImage7_19.getImageName(), figureImage7_19.getPath());
       model.addAttribute(figureImage7_20.getImageName(), figureImage7_20.getPath());
       model.addAttribute(figureImage7_21.getImageName(), figureImage7_21.getPath());
       model.addAttribute(figureImage7_22.getImageName(), figureImage7_22.getPath());
       model.addAttribute(figureImage7_23.getImageName(), figureImage7_23.getPath());
       model.addAttribute(figureImage7_24.getImageName(), figureImage7_24.getPath());
       // 8 ROW
       model.addAttribute(figureImage8_1.getImageName(), figureImage8_1.getPath());
       model.addAttribute(figureImage8_2.getImageName(), figureImage8_2.getPath());
       model.addAttribute(figureImage8_3.getImageName(), figureImage8_3.getPath());
       model.addAttribute(figureImage8_4.getImageName(), figureImage8_4.getPath());
       model.addAttribute(figureImage8_5.getImageName(), figureImage8_5.getPath());
       model.addAttribute(figureImage8_6.getImageName(), figureImage8_6.getPath());
       model.addAttribute(figureImage8_7.getImageName(), figureImage8_7.getPath());
       model.addAttribute(figureImage8_8.getImageName(), figureImage8_8.getPath());
       model.addAttribute(figureImage8_9.getImageName(), figureImage8_9.getPath());
       model.addAttribute(figureImage8_10.getImageName(), figureImage8_10.getPath());
       model.addAttribute(figureImage8_11.getImageName(), figureImage8_11.getPath());
       model.addAttribute(figureImage8_12.getImageName(), figureImage8_12.getPath());
       model.addAttribute(figureImage8_13.getImageName(), figureImage8_13.getPath());
       model.addAttribute(figureImage8_14.getImageName(), figureImage8_14.getPath());
       model.addAttribute(figureImage8_15.getImageName(), figureImage8_15.getPath());
       model.addAttribute(figureImage8_16.getImageName(), figureImage8_16.getPath());
       model.addAttribute(figureImage8_17.getImageName(), figureImage8_17.getPath());
       model.addAttribute(figureImage8_18.getImageName(), figureImage8_18.getPath());
       model.addAttribute(figureImage8_19.getImageName(), figureImage8_19.getPath());
       model.addAttribute(figureImage8_20.getImageName(), figureImage8_20.getPath());
       model.addAttribute(figureImage8_21.getImageName(), figureImage8_21.getPath());
       model.addAttribute(figureImage8_22.getImageName(), figureImage8_22.getPath());
       model.addAttribute(figureImage8_23.getImageName(), figureImage8_23.getPath());
       model.addAttribute(figureImage8_24.getImageName(), figureImage8_24.getPath());
       // 9 ROW
       model.addAttribute(figureImage9_1.getImageName(), figureImage9_1.getPath());
       model.addAttribute(figureImage9_2.getImageName(), figureImage9_2.getPath());
       model.addAttribute(figureImage9_3.getImageName(), figureImage9_3.getPath());
       model.addAttribute(figureImage9_4.getImageName(), figureImage9_4.getPath());
       model.addAttribute(figureImage9_5.getImageName(), figureImage9_5.getPath());
       model.addAttribute(figureImage9_6.getImageName(), figureImage9_6.getPath());
       model.addAttribute(figureImage9_7.getImageName(), figureImage9_7.getPath());
       model.addAttribute(figureImage9_8.getImageName(), figureImage9_8.getPath());
       model.addAttribute(figureImage9_9.getImageName(), figureImage9_9.getPath());
       model.addAttribute(figureImage9_10.getImageName(), figureImage9_10.getPath());
       model.addAttribute(figureImage9_11.getImageName(), figureImage9_11.getPath());
       model.addAttribute(figureImage9_12.getImageName(), figureImage9_12.getPath());
       model.addAttribute(figureImage9_13.getImageName(), figureImage9_13.getPath());
       model.addAttribute(figureImage9_14.getImageName(), figureImage9_14.getPath());
       model.addAttribute(figureImage9_15.getImageName(), figureImage9_15.getPath());
       model.addAttribute(figureImage9_16.getImageName(), figureImage9_16.getPath());
       model.addAttribute(figureImage9_17.getImageName(), figureImage9_17.getPath());
       model.addAttribute(figureImage9_18.getImageName(), figureImage9_18.getPath());
       model.addAttribute(figureImage9_19.getImageName(), figureImage9_19.getPath());
       model.addAttribute(figureImage9_20.getImageName(), figureImage9_20.getPath());
       model.addAttribute(figureImage9_21.getImageName(), figureImage9_21.getPath());
       model.addAttribute(figureImage9_22.getImageName(), figureImage9_22.getPath());
       model.addAttribute(figureImage9_23.getImageName(), figureImage9_23.getPath());
       model.addAttribute(figureImage9_24.getImageName(), figureImage9_24.getPath());
       // 10 ROW
       model.addAttribute(figureImage10_1.getImageName(), figureImage10_1.getPath());
       model.addAttribute(figureImage10_2.getImageName(), figureImage10_2.getPath());
       model.addAttribute(figureImage10_3.getImageName(), figureImage10_3.getPath());
       model.addAttribute(figureImage10_4.getImageName(), figureImage10_4.getPath());
       model.addAttribute(figureImage10_5.getImageName(), figureImage10_5.getPath());
       model.addAttribute(figureImage10_6.getImageName(), figureImage10_6.getPath());
       model.addAttribute(figureImage10_7.getImageName(), figureImage10_7.getPath());
       model.addAttribute(figureImage10_8.getImageName(), figureImage10_8.getPath());
       model.addAttribute(figureImage10_9.getImageName(), figureImage10_9.getPath());
       model.addAttribute(figureImage10_10.getImageName(), figureImage10_10.getPath());
       model.addAttribute(figureImage10_11.getImageName(), figureImage10_11.getPath());
       model.addAttribute(figureImage10_12.getImageName(), figureImage10_12.getPath());
       model.addAttribute(figureImage10_13.getImageName(), figureImage10_13.getPath());
       model.addAttribute(figureImage10_14.getImageName(), figureImage10_14.getPath());
       model.addAttribute(figureImage10_15.getImageName(), figureImage10_15.getPath());
       model.addAttribute(figureImage10_16.getImageName(), figureImage10_16.getPath());
       model.addAttribute(figureImage10_17.getImageName(), figureImage10_17.getPath());
       model.addAttribute(figureImage10_18.getImageName(), figureImage10_18.getPath());
       model.addAttribute(figureImage10_19.getImageName(), figureImage10_19.getPath());
       model.addAttribute(figureImage10_20.getImageName(), figureImage10_20.getPath());
       model.addAttribute(figureImage10_21.getImageName(), figureImage10_21.getPath());
       model.addAttribute(figureImage10_22.getImageName(), figureImage10_22.getPath());
       model.addAttribute(figureImage10_23.getImageName(), figureImage10_23.getPath());
       model.addAttribute(figureImage10_24.getImageName(), figureImage10_24.getPath());


   return model;
   }
}